image: docker:latest

stages:
  - build
  - deploy

variables:
  REGISTRY: 10.3.7.241:5000
  CONTAINER_IMAGE: ${REGISTRY}/notification:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  tags:
    - deployement
  script:
    - docker login ${REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  tags:
    - deployement
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/deployment.yaml
    - kubectl config use-context staging
    - kubectl apply -f kubernetes/deployment.yaml
