variables:
  REGISTRY_DEV: 10.3.7.221:5000
  REGISTRY_STAGING: 10.3.7.241:5000
  CONTAINER_IMAGE_DEV: ${REGISTRY_DEV}/notification:${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_STAGING: ${REGISTRY_STAGING}/notification:${CI_COMMIT_SHORT_SHA}

test-build:
  stage: test
  image: python:3.7-buster
  tags:
    - test
  only:
    refs:
      - jzhang
  script:
    - pip install -r requirements.txt
    - pip install -r tests/test_requirements.txt
    - pytest

test-deploy:
  stage: deploy
  tags:
    - deployement
  only:
    refs:
      - jzhang
  script:
    - echo "deploying test~~"


