# Copyright (C) 2022 Indoc Research
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "5065:8000"
    environment:
      port: 8000
      POSTFIX_URL: mailhog
      POSTFIX_PORT: 1025
      RDS_USER: postgres
      RDS_PWD: postgres
      RDS_HOST: db
      RDS_PORT: 5432
      NOTIFICATIONS_SCHEMA: notifications
      ANNOUNCEMENTS_SCHEMA: announcements
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/notifications
    volumes:
    - .:/usr/src/app
    depends_on:
      - mailhog
      - db
    command:
      sh -c "
        pip install alembic

        alembic upgrade head

        uvicorn run:app --reload --host 0.0.0.0
      "

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: 'postgres:12-alpine'
    ports:
      - 5400:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./migrations/scripts/create_notifications_db.sql:/docker-entrypoint-initdb.d/01.sql
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "8750:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    logging:
      driver: none
    volumes:
      - ./local_config/pgadmin/:/var/lib/pgadmin/
    depends_on:
      - db

networks:
  default:
    external:
      name: pilot-network
