# Copyright (C) 2022 Indoc Research
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: docker:latest

variables:
  REGISTRY_DEV: 10.3.7.221:5000
  REGISTRY_STAGING: 10.3.7.241:5000
  CONTAINER_IMAGE_DEV: ${REGISTRY_DEV}/notification:${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE_STAGING: ${REGISTRY_STAGING}/notification:${CI_COMMIT_SHORT_SHA}

stages:
  - test
  - build
  - deploy

dev-test:
  stage: test
  tags:
    - test
  only:
    refs:
      - k8s-dev
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r tests/test_requirements.txt
    - pytest

dev-build:
  stage: build
  tags:
    - deployement
  only:
    refs:
      - k8s-dev
  script:
    - docker login ${REGISTRY_DEV} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE_DEV} .
    - docker push ${CONTAINER_IMAGE_DEV}

dev-deploy:
  stage: deploy
  tags:
    - deployement
  only:
    refs:
      - k8s-dev
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/dev-deployment.yaml
    - kubectl config use-context dev
    - kubectl apply -f kubernetes/dev-deployment.yaml


staging-build:
  stage: build
  tags:
    - deployement
  only:
    refs:
      - k8s-staging
  script:
    - docker login ${REGISTRY_STAGING} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${CONTAINER_IMAGE_STAGING} .
    - docker push ${CONTAINER_IMAGE_STAGING}

staging-deploy:
  stage: deploy
  tags:
    - deployement
  only:
    refs:
      - k8s-staging
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/staging-deployment.yaml
    - kubectl config use-context staging
    - kubectl apply -f kubernetes/staging-deployment.yaml
