apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: registry-gitlab.indocresearch.org/platform/service_notification:<VERSION>
          ports:
            - containerPort: 5065
          env:
          - name: env
            value: "dev"
          - name: CONFIG_CENTER_ENABLED
            value: "true"
          - name: CONFIG_CENTER_BASE_URL
            value: "http://common.utility:5062/"
          - name: VAULT_URL
            value: "https://vault.vault:8200/v1/vre/app/config"
          - name: VAULT_CRT
            value: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-secret
                key: token
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
spec:
  ports:
  - name: notification
    port: 5065
    targetPort: 5065
  selector:
    app: notification
  type: LoadBalancer
