apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 10.3.7.241:5000/notification:<VERSION>
          ports:
            - containerPort: 5065
          env:
          - name: env
            value: "staging"
          - name: CONFIG_CENTER_ENABLED
            value: "true"
          - name: CONFIG_CENTER_BASE_URL
            value: "http://common.utility:5062/"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
spec:
  ports:
  - name: notification
    port: 5065
    targetPort: 5065
  selector:
    app: notification
  type: ClusterIP
